# Generated by Django 3.2.6 on 2021-09-06 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('administrar', 'Permite asignar permisos a los usuarios'), ('auditar', 'Permite auditar la información del sistema'), ('crear_proyecto', 'Permite crear proyectos nuevos')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('duracion_sprint', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Inicio (mm/dd/yy)')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fin (mm/dd/yy)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, null=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creador_set', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ManyToManyField(related_name='equipo_set', through='sgp.Participa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('administrar_equipo', 'Permite asignar permisos a los usuarios'), ('gestionar_proyecto', 'Permite auditar la información del sistema'), ('pila_producto', 'Permite crear proyectos nuevos'), ('desarrollo', 'Permite crear proyectos nuevos'), ('vista', 'Permite ver información del proyecto')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='participa',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.proyecto'),
        ),
        migrations.AddField(
            model_name='participa',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.role'),
        ),
        migrations.AddField(
            model_name='participa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
