# Generated by Django 3.2.6 on 2021-10-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('administrar', 'Permite asignar permisos a los usuarios'), ('auditar', 'Permite auditar la información del sistema'), ('crear_proyecto', 'Permite crear proyectos nuevos')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipaSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_disponibles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('duracion_sprint', models.IntegerField(blank=True, null=True, verbose_name='Duración de los sprints')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(null=True, verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('I', 'Iniciado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=50)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creador_set', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ManyToManyField(related_name='equipo_set', through='sgp.Participa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('administrar_equipo', 'administración de equipo'), ('gestionar_proyecto', 'gestión de proyecto'), ('pila_producto', 'gestión de pila de producto'), ('desarrollo', 'desarrollo'), ('vista', 'acceso al proyecto')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('I', 'Iniciado'), ('F', 'Finalizado')], default='P', max_length=50)),
                ('equipo', models.ManyToManyField(through='sgp.ParticipaSprint', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('I', 'Iniciado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=50)),
                ('prioridad', models.IntegerField(choices=[(1, 'Muy Alta'), (2, 'Alta'), (3, 'Normal'), (4, 'Baja'), (5, 'Muy baja')], default=3)),
                ('horas_estimadas', models.IntegerField(null=True)),
                ('horas_trabajadas', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='sgp.proyecto')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_backlog', to='sgp.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='participasprint',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.sprint'),
        ),
        migrations.AddField(
            model_name='participasprint',
            name='user_stories',
            field=models.ManyToManyField(to='sgp.UserStory'),
        ),
        migrations.AddField(
            model_name='participasprint',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participa',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.proyecto'),
        ),
        migrations.AddField(
            model_name='participa',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.role'),
        ),
        migrations.AddField(
            model_name='participa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.userstory')),
            ],
        ),
    ]
