# Generated by Django 3.2.6 on 2021-10-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participasprint',
            old_name='horas_disponibles',
            new_name='horas_diarias',
        ),
    ]
