# Generated by Django 3.2.6 on 2021-12-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incremento',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
