# Generated by Django 3.2.6 on 2021-08-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_auto_20210824_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': (), 'permissions': [('administrar', 'Permite asignar permisos a los usuarios'), ('auditar', 'Permite auditar la información del sistema'), ('crear_proyecto', 'Permite crear proyectos nuevos')]},
        ),
    ]
