# Generated by Django 3.2.6 on 2021-12-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0002_alter_incremento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
