# Generated by Django 3.2.6 on 2021-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=400, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio del proyecto')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin del proyecto')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=200, null=True)),
            ],
        ),
    ]
