# Generated by Django 3.2.6 on 2021-10-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0003_alter_userstory_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incremento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('horas', models.IntegerField(default=0)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.userstory')),
            ],
        ),
    ]
