# Generated by Django 3.2.6 on 2021-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0004_auto_20210928_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Muy baja'), (2, 'Baja'), (3, 'Normal'), (4, 'Alta'), (5, 'Muy alta')]),
        ),
    ]
