# Generated by Django 3.2.6 on 2021-09-03 04:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sgp', '0005_auto_20210902_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('administrar_equipo', 'Permite asignar permisos a los usuarios'), ('gestionar_proyecto', 'Permite auditar la información del sistema'), ('pila_producto', 'Permite crear proyectos nuevos'), ('desarrollo', 'Permite crear proyectos nuevos')]},
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.proyecto')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
