# Generated by Django 3.2.6 on 2021-10-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0005_incremento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incremento',
            name='user_story',
        ),
        migrations.RemoveField(
            model_name='incremento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='incremento',
            name='participasprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgp.participasprint'),
        ),
    ]
