# Generated by Django 3.2.6 on 2021-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0005_alter_userstory_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='horas_estimadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='horas_trabajadas',
            field=models.IntegerField(default=0),
        ),
    ]
