# Generated by Django 3.2.6 on 2021-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0006_auto_20210928_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('I', 'Iniciado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=50),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(choices=[(1, 'Muy Alta'), (2, 'Alta'), (3, 'Normal'), (4, 'Baja'), (5, 'Muy baja')]),
        ),
    ]
