# Generated by Django 3.2.6 on 2021-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0006_auto_20210902_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
