# Generated by Django 3.2.6 on 2021-11-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0006_auto_20211025_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_fin_original',
            field=models.DateField(null=True),
        ),
    ]
