# Generated by Django 3.2.6 on 2021-11-28 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0007_sprint_fecha_fin_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incremento',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
