# Generated by Django 3.2.6 on 2021-09-30 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0007_auto_20210928_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='equipo',
        ),
        migrations.CreateModel(
            name='ParticipaSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_disponibles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.role')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgp.sprint')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
