# Generated by Django 3.2.6 on 2021-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0008_auto_20210902_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(null=True, verbose_name='Fin (mm/dd/yy)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Inicio (mm/dd/yy)'),
        ),
    ]
