# Generated by Django 3.2.6 on 2021-09-30 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0008_auto_20210930_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='equipo',
            field=models.ManyToManyField(through='sgp.ParticipaSprint', to=settings.AUTH_USER_MODEL),
        ),
    ]
