# Generated by Django 3.2.6 on 2021-09-30 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0009_sprint_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participasprint',
            name='user_stories',
            field=models.ManyToManyField(to='sgp.UserStory'),
        ),
        migrations.AlterField(
            model_name='participasprint',
            name='horas_disponibles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_backlog', to='sgp.sprint'),
        ),
    ]
