# Generated by Django 3.2.6 on 2021-09-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0009_auto_20210902_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50, null=True),
        ),
    ]
