# Generated by Django 3.2.6 on 2021-09-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0006_auto_20210903_0003'),
        ('sgp', '0009_auto_20210902_1211'),
    ]

    operations = [
    ]
