# Generated by Django 3.2.6 on 2021-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0010_alter_proyecto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creador',
            field=models.CharField(default='user.id', max_length=200, null=True),
        ),
    ]
