# Generated by Django 3.2.6 on 2021-10-11 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0010_auto_20210930_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
    ]
