# Generated by Django 3.2.6 on 2021-09-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0010_merge_0006_auto_20210903_0003_0009_auto_20210902_1211'),
        ('sgp', '0011_alter_proyecto_creador'),
    ]

    operations = [
    ]
