# Generated by Django 3.2.6 on 2021-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgp', '0011_alter_proyecto_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='creador',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
